### ISSUE TITLE
Question about XBOX directories

### ISSUE THREAD

**Issue by DGKSK8LIFE** [TheAlePower/TeamFortress2#1]
Hey, just a quick question about the source code, what exactly are the `xbox` directories for? Is this for xbox controller binds or the alleged console port that didn't end up happening early on in the game's lifespan? Ty!

**Comment by infirms** [comment]
> 
> 
> Hey, just a quick question about the source code, what exactly are the `xbox` directories for? Is this for xbox controller binds or the alleged console port that didn't end up happening early on in the game's lifespan? Ty!

Hello. tf2 has been released on 7th generation consoles. So this might be parts of old code related to xbox360 release.

**Comment by DGKSK8LIFE** [comment]
Ty @infirms
