### ISSUE TITLE
Valve Project Creator complains about missing files on running the bat fle

### ISSUE THREAD

**Issue by conneath** [TheAlePower/TeamFortress2#2]
```
Parsing: socketlib.vpc
ERROR: Cannot open socketlib.vpc
```
on trying to make the "Everything" solution

**Comment by barn-advisor** [comment]
also trying to make just the game solutions works but complains about libprotobuf missing when you try to compile it

**Comment by BananaSplit2213** [comment]
I have the same problem, did you find a fix by any chance?

**Comment by barn-advisor** [comment]
nope

> 
> 
> I have the same problem, did you find a fix by any chance?

nope, PROBABLY you could fix this by copying the game code from here to a fresh source sdk 2013 copy, but you can't mess with the Engine or GameUI this way only the game code

**Comment by NoXeDev** [comment]
The leak has been release without libs. You need to find it for build the project. Good luck

**Comment by conneath** [comment]
well thats not really helpful but ok
i got most of the leak working by just copying game code to a source sdk 2013 code folder, not the engine code though

**Comment by TheAlePower** [comment]
Reopened, back from my semi-forced hybernation. Currently investigating on the issue. Will keep thread updated

**Comment by TheAlePower** [comment]
https://developer.valvesoftware.com/wiki/Editing_VPC_scripts this is the closest that i can do in matters of being helpful. The leak did not have that specific lib, and neither did CSGO. Trying to find the original leak so i can check if it had anything. Same for #3 #

**Comment by omaemae** [comment]
it's not just socketlib, it's in fact all of this: https://cdn.discordapp.com/attachments/413430340388913171/876129880121704518/message.txt

i guess the leaker decided to not include any third-party libraries with the code

**Comment by TheAlePower** [comment]
that is an entire repertory of headaches that cannot be fixed
