### ISSUE TITLE
VPC Complaining about a missing file

### ISSUE THREAD

**Issue by BananaSplit2213** [TheAlePower/TeamFortress2#3]
I tried running createallprojects.bat but its complaining about a missing file (socketlib.vpc).

**Comment by TheAlePower** [comment]
I am back from my semi-forced hybernation, currently investigating

**Comment by Bruh-cell-cell** [comment]
Anything come for your investigation?

**Comment by TheAlePower** [comment]
#2 has this problem too, i've written the response there to prevent confusion

**Comment by TheAlePower** [comment]
#2 contains my reply, as well a list of libs that are also missing. headache not worth the hassle, if it is even fixable. WONTFIX
